name: Susak gitaction java

# Определяем, когда запускать workflow
on:
  push:
    branches:
      - main  # Запускать workflow при push в основную ветку
  workflow_dispatch:  # Позволяет запускать workflow вручную через интерфейс GitHub
# Определяем задачи
jobs:
  build:
    # Используем общедоступный runner Ubuntu в Github runner нет ORACLE lINUX только ubuntu
    runs-on: ubuntu-latest
    
    # клонирование текущего репозитария 
    steps:
         - name: Checkout code
           uses: actions/checkout@v3
           
 # Устанавливаем JDK
         - name: Set up JDK 11
           uses: actions/setup-java@v3
             with:
               distribution: 'temurin'  # Используем JDK от Temurin (OpenJDK)
               java-version: '11'       # Укажите версию JDK, которая требуется вашему проекту

      # Скачиваем и устанавливаем зависимости, собираем проект
          - name: Build with Maven
            run: mvn clean install
